apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: javajava-java-sample-my1m
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: javajava-java-sample-my1m
    app.kubernetes.io/part-of: e2e-java
  name: javajava-java-sample-my1m
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: javajava-java-sample-my1m
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: javajava-java-sample-my1m
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ayfv-tenant/e2e-java/javajava-java-sample-my1m@sha256:567bd0e607b96df7f1a4147545bbd3254696b83ed5d964b86e979921bbf49bfb
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
